---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Jeremy Ferguson"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-important}
## Memo format

Like all other submissions for this course, we expect the memo to be neat and well organized.

You should make this document your own. This is a template. To help with this we have added a date to the yaml above (good whenever writing memos). You should remove this block when making this document your own.

:::

::: {.callout-tip icon=false}

## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[https://github.com/stat301-1-2023-fall/final-project-1-jeremyferg.git](https://github.com/stat301-1-2023-fall/final-project-1-jeremyferg.git)

:::

::: {.callout-warning}
GitHub (free account) cannot store large files. If you try to commit and push a large dataset you will have an ERROR! Any file over 100 MB (100,000 KB) needs to be added to the `.gitignore` file BEFORE committing.

**We may need to do that for files in your final project!**
:::

## Project Purpose

In my project, I will analyze the correlation between stocks of video game publishers and industry-related events occurring over the past 10 years. Events in this analysis are any media occurrences that contribute to the popularity of the game (ex: game review, game awards, etc.). I will examine the effect a publisher’s own events have on their stock and the effects events related to the publisher have on their stock (ex: a game release from an other publisher specialized in the same game genre). I will analyze these correlations by creating a time series dataset that records stocks and events per day. 

## Data source

My data source will consist of a mixture of existing datasets and data I gather through web scraping. I ultimately plan to create a time series data set, where between Jun. 2013 and Jun. 2023, I record the stock of the video game publisher and any events I’ve identified occurring on that date that could alter stocks. The events I intend to focus on are game release dates, reviews, esports earnings/tournaments, and game awards. 

I will retrieve stock data on Yahoo Finance. These datasets will have 6 columns excluding the date column. I plan to compare 10 different publisher’s stocks: [Nintendo](https://finance.yahoo.com/quote/NTDOY/), [EA](https://finance.yahoo.com/quote/EA/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Activision Blizzard](https://finance.yahoo.com/quote/ATVI/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Ubisoft](https://finance.yahoo.com/quote/UBI.PA/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Square Enix](https://finance.yahoo.com/quote/9684.T/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Bandai Namco](https://finance.yahoo.com/quote/7832.T/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Sega](https://finance.yahoo.com/quote/6460.T/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Take-Two](https://finance.yahoo.com/quote/TTWO/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), [Capcom](https://finance.yahoo.com/quote/9697.T/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true), and [Konami](https://finance.yahoo.com/quote/9766.T/history?period1=1370044800&period2=1685577600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true). 

I found a few datasets that recorded video game release dates, but these datasets were either missing games or were published years ago. So, I will scrape this information from [Wikipedia](https://en.wikipedia.org/wiki/Category:Video_games_by_year). I plan to web scrape game names, game series, publishers, release dates, genre of game, and game modes. I’ve created a small example of what this dataset would look like using web scraping (shown in the data quality section). The goal, of course, is to create a function that can make this dataset at once. 

I found the same dataset issue when looking at data for game awards and game reviews. Concerning game awards, I will be scraping Wikipedia pages for [The Game Awards results](https://en.wikipedia.org/wiki/The_Game_Awards_2022). The Game Awards is the annual, most acclaimed awards ceremony in the video game industry. I am currently planning to have the date of the award, game name, award category, publisher, and win (whether or not the nominee won) as the collected data. Each observation in this dataset will be a nominee, so there is no need for a nominee column. The number of nominees and wins a game/publisher receives will also prove to be useful in the analysis. 

I will be web-scraping video game review information from [Metacritic](https://www.metacritic.com/), which hosts an aggregate set of game reviews similar to Rotten Tomatoes. My intended columns are game reviewed, review date, critic or user (TRUE if the review was done by a critic), score, average critic score yesterday ( average score of all critics before the observation’s review date), and average user score yesterday (similar meaning).

Finally, I was able to find an extensive, up-to-date dataset of [esports-related games and earnings from tournaments](https://www.kaggle.com/datasets/rankirsh/esports-earnings). Observations are recorded every month (instead of daily like my other data). Along with the monthly date, the dataset’s columns are game, monthly earnings, number of players getting a share of the earnings, and the number of tournaments that month. I may web scrape the data’s [original site](https://www.esportsearnings.com/) to get daily records, as exact tournament dates and earnings are made public. However, I believe I can produce good information concerning esports with monthly records and currently do not intend on scraping this site. 

Blah blah blah^[where blah blah came from, an example of footnote]

## Why this data

Blah blah blah^[another footnote]

## Data quality & complexity check

Blah blah blah

## Potential data issues

Blah blah blah

## Misc

Blah Blah
